import { NextResponse } from 'next/server';

export async function GET() {
  try {
    const frameworks = [
      {
        id: 'soc2',
        name: 'SOC 2 Type II',
        score: 94,
        status: 'pass',
        controlsPassed: 47,
        controlsTotal: 50,
        lastAssessed: new Date(Date.now() - 86400000).toISOString(),
        controls: [
          { id: 'CC6.1', name: 'Logical and Physical Access Controls', category: 'Security', status: 'pass', evidence: 'Automated access review completed — 0 violations' },
          { id: 'CC6.2', name: 'System Account Management', category: 'Security', status: 'pass', evidence: 'All accounts reviewed quarterly' },
          { id: 'CC6.3', name: 'Data Encryption Standards', category: 'Security', status: 'pass', evidence: 'AES-256 at rest, TLS 1.3 in transit' },
          { id: 'CC7.1', name: 'Network Intrusion Detection', category: 'Security', status: 'pass', evidence: 'IDS active on all perimeters' },
          { id: 'CC7.2', name: 'Incident Response Procedures', category: 'Security', status: 'pass', evidence: 'IR plan tested 30 days ago' },
          { id: 'CC8.1', name: 'Change Management Controls', category: 'Security', status: 'pass', evidence: 'All changes approved via CAB' },
          { id: 'CC1.2', name: 'Control Environment & Tone', category: 'Governance', status: 'pass', evidence: 'Board-level security review active' },
          { id: 'CC1.3', name: 'Risk Assessment Process', category: 'Governance', status: 'pass', evidence: 'Quarterly risk assessments completed' },
          { id: 'CC3.1', name: 'Risk Mitigation Strategy', category: 'Risk', status: 'pass', evidence: 'All critical risks mitigated' },
          { id: 'CC3.2', name: 'Vendor Risk Management', category: 'Risk', status: 'fail', evidence: '2 vendor assessments overdue' },
          { id: 'CC4.1', name: 'Monitoring Activities', category: 'Operations', status: 'pass', evidence: '24/7 SOC monitoring active' },
          { id: 'CC4.2', name: 'Service Level Agreements', category: 'Operations', status: 'pass', evidence: 'All SLAs met within threshold' },
        ],
      },
      {
        id: 'hipaa',
        name: 'HIPAA',
        score: 87,
        status: 'warn',
        controlsPassed: 156,
        controlsTotal: 180,
        lastAssessed: new Date(Date.now() - 172800000).toISOString(),
        controls: [
          { id: '§164.308(a)(1)', name: 'Security Management Process', category: 'Administrative', status: 'pass', evidence: 'Risk analysis completed annually' },
          { id: '§164.308(a)(3)', name: 'Workforce Security', category: 'Administrative', status: 'pass', evidence: 'Background checks for all PHI access' },
          { id: '§164.308(a)(4)', name: 'Information Access Management', category: 'Administrative', status: 'pass', evidence: 'Role-based access enforced' },
          { id: '§164.308(a)(5)', name: 'Security Awareness Training', category: 'Administrative', status: 'warn', evidence: '3 staff overdue for annual training' },
          { id: '§164.308(a)(6)', name: 'Contingency Planning', category: 'Administrative', status: 'pass', evidence: 'DR plan tested successfully' },
          { id: '§164.308(a)(7)', name: 'Evaluation', category: 'Administrative', status: 'pass', evidence: 'Annual security evaluation completed' },
          { id: '§164.310(a)', name: 'Facility Access Controls', category: 'Physical', status: 'pass', evidence: 'Badge access enforced' },
          { id: '§164.310(b)', name: 'Workstation Use', category: 'Physical', status: 'pass', evidence: 'Auto-lock policies enforced' },
          { id: '§164.310(d)', name: 'Device Controls', category: 'Physical', status: 'fail', evidence: '2 unencrypted devices found in inventory' },
          { id: '§164.312(a)', name: 'Access Controls', category: 'Technical', status: 'pass', evidence: 'MFA enforced for all systems' },
          { id: '§164.312(b)', name: 'Audit Controls', category: 'Technical', status: 'pass', evidence: 'Comprehensive audit logging active' },
          { id: '§164.312(e)', name: 'Transmission Security', category: 'Technical', status: 'pass', evidence: 'All PHI transmitted via TLS 1.3' },
        ],
      },
      {
        id: 'pcidss',
        name: 'PCI-DSS v4.0',
        score: 91,
        status: 'pass',
        controlsPassed: 218,
        controlsTotal: 240,
        lastAssessed: new Date(Date.now() - 259200000).toISOString(),
        controls: [
          { id: '1.1', name: 'Network Firewall Configuration', category: 'Network', status: 'pass', evidence: 'Firewall rules reviewed monthly' },
          { id: '1.2', name: 'Network Security Controls', category: 'Network', status: 'pass', evidence: 'Direct public access prohibited' },
          { id: '2.1', name: 'Strong Default Configurations', category: 'Network', status: 'pass', evidence: 'Hardening baseline applied to all systems' },
          { id: '2.2', name: 'System Component Inventory', category: 'Network', status: 'pass', evidence: 'CMDB updated within 24h of changes' },
          { id: '3.1', name: 'Cardholder Data Inventory', category: 'Data', status: 'pass', evidence: 'CHD locations documented and minimized' },
          { id: '3.2', name: 'Storage of PAN', category: 'Data', status: 'pass', evidence: 'PAN truncated or masked where stored' },
          { id: '4.1', name: 'Strong Cryptography', category: 'Data', status: 'pass', evidence: 'AES-256 for PAN at rest' },
          { id: '5.1', name: 'Malware Protection', category: 'Security', status: 'pass', evidence: 'EDR deployed on all endpoints' },
          { id: '6.1', name: 'Secure Systems Development', category: 'Security', status: 'pass', evidence: 'Secure SDLC enforced' },
          { id: '7.1', name: 'Access to Cardholder Data', category: 'Access', status: 'pass', evidence: 'Least privilege enforced via RBAC' },
          { id: '8.1', name: 'User Identification', category: 'Access', status: 'warn', evidence: '1 service account needs MFA remediation' },
          { id: '11.1', name: 'Security Testing', category: 'Testing', status: 'pass', evidence: 'Quarterly vulnerability scans passed' },
        ],
      },
      {
        id: 'iso27001',
        name: 'ISO 27001:2022',
        score: 82,
        status: 'warn',
        controlsPassed: 102,
        controlsTotal: 125,
        lastAssessed: new Date(Date.now() - 345600000).toISOString(),
        controls: [
          { id: 'A.5.1', name: 'Information Security Policies', category: 'Organizational', status: 'pass', evidence: 'ISMS policies updated Q2 2026' },
          { id: 'A.5.2', name: 'Information Security Roles', category: 'Organizational', status: 'pass', evidence: 'CISO and security team defined' },
          { id: 'A.5.3', name: 'Segregation of Duties', category: 'Organizational', status: 'pass', evidence: 'SoD matrix implemented' },
          { id: 'A.5.4', name: 'Management Responsibilities', category: 'Organizational', status: 'pass', evidence: 'Monthly security review meetings' },
          { id: 'A.5.5', name: 'Contact with Authorities', category: 'Organizational', status: 'pass', evidence: 'Law enforcement contacts maintained' },
          { id: 'A.6.1', name: 'Screening', category: 'HR', status: 'warn', evidence: '2 contractors pending background check' },
          { id: 'A.6.2', name: 'Terms and Conditions', category: 'HR', status: 'pass', evidence: 'NDAs current for all staff' },
          { id: 'A.7.1', name: 'Physical Security Perimeters', category: 'Physical', status: 'pass', evidence: 'Data center access controlled' },
          { id: 'A.8.1', name: 'User Endpoint Devices', category: 'Technology', status: 'pass', evidence: 'MDM enforced on all endpoints' },
          { id: 'A.8.2', name: 'Privileged Access Rights', category: 'Technology', status: 'fail', evidence: '3 orphaned admin accounts found' },
          { id: 'A.8.3', name: 'Information Access Restriction', category: 'Technology', status: 'pass', evidence: 'DLP policies enforced' },
          { id: 'A.9.1', name: 'Vulnerability Management', category: 'Supplier', status: 'pass', evidence: 'Continuous vulnerability scanning active' },
        ],
      },
      {
        id: 'nist',
        name: 'NIST CSF 2.0',
        score: 96,
        status: 'pass',
        controlsPassed: 105,
        controlsTotal: 109,
        lastAssessed: new Date(Date.now() - 432000000).toISOString(),
        controls: [
          { id: 'ID.AM-1', name: 'Asset Inventory', category: 'Identify', status: 'pass', evidence: 'Automated asset discovery active' },
          { id: 'ID.RA-1', name: 'Risk Assessment', category: 'Identify', status: 'pass', evidence: 'Continuous risk assessment operational' },
          { id: 'PR.AC-1', name: 'Identity Management', category: 'Protect', status: 'pass', evidence: 'SSO with MFA for all users' },
          { id: 'PR.DS-1', name: 'Data-at-Rest Protection', category: 'Protect', status: 'pass', evidence: 'Encryption enforced across all data stores' },
          { id: 'PR.DS-2', name: 'Data-in-Transit Protection', category: 'Protect', status: 'pass', evidence: 'TLS 1.3 mandatory on all connections' },
          { id: 'PR.IP-1', name: 'Change Management', category: 'Protect', status: 'pass', evidence: 'Automated change control pipeline' },
          { id: 'DE.AE-1', name: 'Event Logging', category: 'Detect', status: 'pass', evidence: 'Centralized SIEM with 365-day retention' },
          { id: 'DE.CM-1', name: 'Continuous Monitoring', category: 'Detect', status: 'pass', evidence: '24/7 monitoring with automated alerting' },
          { id: 'RS.RP-1', name: 'Recovery Planning', category: 'Recover', status: 'pass', evidence: 'DR plans tested semi-annually' },
          { id: 'RS.CO-1', name: 'Incident Response', category: 'Recover', status: 'pass', evidence: 'IR team with <15min response SLA' },
          { id: 'RC.CO-1', name: 'Communication', category: 'Recover', status: 'pass', evidence: 'Crisis communication plan in place' },
          { id: 'RC.RP-1', name: 'Recovery Execution', category: 'Recover', status: 'pass', evidence: 'RPO/RTO targets met in last drill' },
        ],
      },
      {
        id: 'gdpr',
        name: 'GDPR',
        score: 88,
        status: 'warn',
        controlsPassed: 75,
        controlsTotal: 85,
        lastAssessed: new Date(Date.now() - 518400000).toISOString(),
        controls: [
          { id: 'Art.5(1)', name: 'Lawfulness of Processing', category: 'Principles', status: 'pass', evidence: 'Legal basis documented for all data' },
          { id: 'Art.5(2)', name: 'Purpose Limitation', category: 'Principles', status: 'pass', evidence: 'Processing purposes clearly defined' },
          { id: 'Art.6', name: 'Consent Mechanisms', category: 'Lawful Basis', status: 'pass', evidence: 'Granular consent management active' },
          { id: 'Art.13', name: 'Information Provision', category: 'Transparency', status: 'pass', evidence: 'Privacy notices current and accessible' },
          { id: 'Art.15', name: 'Right of Access', category: 'Data Subject Rights', status: 'pass', evidence: 'DSAR portal with <72h response' },
          { id: 'Art.17', name: 'Right to Erasure', category: 'Data Subject Rights', status: 'pass', evidence: 'Automated erasure pipeline operational' },
          { id: 'Art.20', name: 'Data Portability', category: 'Data Subject Rights', status: 'warn', evidence: '2 systems need export format update' },
          { id: 'Art.25', name: 'Data Protection by Design', category: 'Technical Measures', status: 'pass', evidence: 'PbD embedded in SDLC' },
          { id: 'Art.30', name: 'Records of Processing', category: 'Accountability', status: 'pass', evidence: 'ROP maintained and auditable' },
          { id: 'Art.32', name: 'Security of Processing', category: 'Security', status: 'pass', evidence: 'Appropriate technical measures in place' },
          { id: 'Art.33', name: 'Breach Notification', category: 'Incidents', status: 'pass', evidence: 'Breach notification process tested' },
          { id: 'Art.35', name: 'Data Protection Impact Assessment', category: 'Accountability', status: 'warn', evidence: '1 new processing activity needs DPIA' },
        ],
      },
    ];

    return NextResponse.json({
      overallScore: Math.round(frameworks.reduce((s, f) => s + f.score, 0) / frameworks.length),
      lastAssessed: new Date().toISOString(),
      frameworks,
    });
  } catch (error) {
    console.error('Compliance API error:', error);
    return NextResponse.json({ error: 'Failed to fetch compliance data' }, { status: 500 });
  }
}
