import { withProtection } from '@/lib/api-protection';
import { db } from '@/lib/db';
import { NextRequest, NextResponse } from 'next/server';

// ── Report Format Types ─────────────────────────────────────────────

type ReportFormat = 'json' | 'html' | 'markdown';

/**
 * Generate a markdown-formatted security assessment report from scan data.
 */
function generateMarkdownReport(
  scan: {
    id: string;
    riskScore: number;
    totalVulns: number;
    criticalCount: number;
    highCount: number;
    mediumCount: number;
    lowCount: number;
    infoCount: number;
    startedAt: Date;
    completedAt: Date | null;
    scanType: string;
    triggeredBy: string;
    complianceScore: number;
    target: { domain: string; ip: string | null };
    findings: {
      title: string;
      severity: string;
      description: string;
      category: string;
      asset: string;
      remediation: string | null;
      cve: string | null;
      cvss: number | null;
    }[];
  }
): string {
  const domain = scan.target.domain;
  const timestamp = scan.completedAt
    ? scan.completedAt.toISOString()
    : scan.startedAt.toISOString();

  const lines: string[] = [];

  // ── Header ──
  lines.push(`# ReconPro Security Assessment Report`);
  lines.push('');
  lines.push(`## Target: ${domain}`);
  if (scan.target.ip) {
    lines.push(`**IP Address:** ${scan.target.ip}`);
  }
  lines.push(`**Scan Date:** ${timestamp}`);
  lines.push(`**Scan Type:** ${scan.scanType}`);
  lines.push(`**Triggered By:** ${scan.triggeredBy}`);
  lines.push('');

  // ── Executive Summary ──
  lines.push('## Executive Summary');
  lines.push('');
  lines.push(`**Overall Risk Score:** ${scan.riskScore}/100`);
  lines.push(`**Compliance Score:** ${scan.complianceScore}/100`);
  lines.push(`**Total Findings:** ${scan.totalVulns}`);
  lines.push('');
  lines.push('| Severity | Count |');
  lines.push('|----------|-------|');
  lines.push(`| Critical | ${scan.criticalCount} |`);
  lines.push(`| High     | ${scan.highCount} |`);
  lines.push(`| Medium   | ${scan.mediumCount} |`);
  lines.push(`| Low      | ${scan.lowCount} |`);
  lines.push(`| Info     | ${scan.infoCount} |`);
  lines.push('');

  // ── Findings by Severity ──
  const severityOrder = ['critical', 'high', 'medium', 'low', 'info'] as const;

  lines.push('## Findings by Severity');
  lines.push('');

  for (const severity of severityOrder) {
    const findings = scan.findings.filter((f) => f.severity === severity);
    if (findings.length === 0) continue;

    lines.push(`### ${severity.charAt(0).toUpperCase() + severity.slice(1)} (${findings.length})`);
    lines.push('');

    for (const finding of findings) {
      lines.push(`**${finding.title}** (${finding.severity}) — ${finding.description}`);
      lines.push(`- **Asset:** ${finding.asset}`);
      lines.push(`- **Category:** ${finding.category}`);
      if (finding.cve) {
        lines.push(`- **CVE:** ${finding.cve}`);
      }
      if (finding.cvss !== null) {
        lines.push(`- **CVSS:** ${finding.cvss}`);
      }
      lines.push('');
    }
  }

  // ── Recommendations ──
  lines.push('## Recommendations');
  lines.push('');

  const findingsWithRemediation = scan.findings.filter(
    (f) => f.remediation && f.remediation.trim().length > 0
  );

  if (findingsWithRemediation.length === 0) {
    lines.push('No specific remediation guidance available for the identified findings.');
  } else {
    // Group recommendations by severity
    for (const severity of severityOrder) {
      const recs = findingsWithRemediation.filter((f) => f.severity === severity);
      if (recs.length === 0) continue;

      for (const rec of recs) {
        lines.push(`- **[${severity.toUpperCase()}]** ${rec.title}: ${rec.remediation}`);
      }
    }
  }

  lines.push('');
  lines.push('---');
  lines.push(`*Report generated by ReconPro on ${new Date().toISOString()}*`);

  return lines.join('\n');
}

/**
 * Wrap markdown content in a basic HTML document structure.
 */
function markdownToHtml(markdown: string, domain: string): string {
  // Convert markdown to simple HTML
  const htmlBody = markdown
    // Headers
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    // Bold
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    // Italic
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    // Horizontal rule
    .replace(/^---$/gm, '<hr />')
    // List items
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    // Table rows (simplified)
    .replace(/\|(.+)\|/g, (_match, content: string) => {
      const cells = content
        .split('|')
        .map((c: string) => c.trim())
        .filter(Boolean);
      // Skip separator rows
      if (cells.every((c: string) => /^-+$/.test(c))) return '';
      const tag = 'td';
      const row = cells.map((c: string) => `<${tag}>${c}</${tag}>`).join('');
      return `<tr>${row}</tr>`;
    })
    // Paragraphs — wrap non-tag lines
    .split('\n')
    .map((line: string) => {
      const trimmed = line.trim();
      if (
        !trimmed ||
        trimmed.startsWith('<h') ||
        trimmed.startsWith('<li') ||
        trimmed.startsWith('<tr') ||
        trimmed.startsWith('<hr')
      ) {
        return line;
      }
      return `<p>${trimmed}</p>`;
    })
    .join('\n');

  // Wrap list items in <ul>
  const withLists = htmlBody.replace(
    /(<li>.*?<\/li>)(?:\n<li>.*?<\/li>)*/gs,
    (match: string) => `<ul>${match}</ul>`
  );

  // Wrap table rows in <table>
  const withTable = withLists.replace(
    /(<tr>.*?<\/tr>)(?:\n<tr>.*?<\/tr>)*/gs,
    (match: string) => `<table border="1" cellpadding="6" cellspacing="0">${match}</table>`
  );

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>ReconPro Security Report — ${domain}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; color: #1a1a1a; line-height: 1.6; }
    h1 { color: #0a0a0a; border-bottom: 2px solid #e5e7eb; padding-bottom: 0.5rem; }
    h2 { color: #111827; margin-top: 2rem; }
    h3 { color: #374151; }
    table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
    th, td { border: 1px solid #d1d5db; padding: 8px 12px; text-align: left; }
    th { background: #f3f4f6; font-weight: 600; }
    ul { padding-left: 1.5rem; }
    li { margin-bottom: 0.5rem; }
    hr { border: none; border-top: 1px solid #e5e7eb; margin: 2rem 0; }
    strong.critical { color: #dc2626; }
    strong.high { color: #ea580c; }
    strong.medium { color: #d97706; }
    strong.low { color: #65a30d; }
    strong.info { color: #6b7280; }
  </style>
</head>
<body>
${withTable}
</body>
</html>`;
}

/**
 * GET /api/reports
 *
 * Generates reports from scan data in json, markdown, or html format.
 *
 * Query params:
 * - scanId (optional) — specific scan to report on
 * - format — json (default), html, markdown
 */
export async function GET(request: NextRequest) {
  const { error } = await withProtection(request, {
    rateLimit: { maxRequests: 30, windowMs: 60_000 },
  });
  if (error) return error;

  try {
    const { searchParams } = new URL(request.url);
    const scanId = searchParams.get('scanId');
    const format = (searchParams.get('format') || 'json') as ReportFormat;

    // Validate format
    if (!['json', 'html', 'markdown'].includes(format)) {
      return NextResponse.json(
        { error: `Invalid format '${format}'. Supported: json, html, markdown` },
        { status: 400 }
      );
    }

    // Fetch scan data
    let scan;
    if (scanId) {
      scan = await db.scan.findUnique({
        where: { id: scanId },
        include: {
          target: true,
          findings: {
            orderBy: [{ severity: 'desc' }, { createdAt: 'desc' }],
          },
        },
      });

      if (!scan) {
        return NextResponse.json(
          { error: `Scan '${scanId}' not found` },
          { status: 404 }
        );
      }
    } else {
      scan = await db.scan.findFirst({
        orderBy: { startedAt: 'desc' },
        include: {
          target: true,
          findings: {
            orderBy: [{ severity: 'desc' }, { createdAt: 'desc' }],
          },
        },
      });

      if (!scan) {
        return NextResponse.json(
          { error: 'No scans available to report' },
          { status: 404 }
        );
      }
    }

    // Format response based on requested format
    switch (format) {
      case 'json':
        return NextResponse.json({ scan });

      case 'markdown': {
        const markdown = generateMarkdownReport(scan);
        return new NextResponse(markdown, {
          status: 200,
          headers: {
            'Content-Type': 'text/markdown; charset=utf-8',
            'Content-Disposition': `inline; filename="reconpro-report-${scan.target.domain}-${scan.startedAt.toISOString().slice(0, 10)}.md"`,
          },
        });
      }

      case 'html': {
        const markdown = generateMarkdownReport(scan);
        const html = markdownToHtml(markdown, scan.target.domain);
        return new NextResponse(html, {
          status: 200,
          headers: {
            'Content-Type': 'text/html; charset=utf-8',
            'Content-Disposition': `inline; filename="reconpro-report-${scan.target.domain}-${scan.startedAt.toISOString().slice(0, 10)}.html"`,
          },
        });
      }

      default: {
        return NextResponse.json(
          { error: `Unsupported format: ${format}` },
          { status: 400 }
        );
      }
    }
  } catch (err) {
    console.error('Report generation error:', err);
    return NextResponse.json(
      { error: 'Failed to generate report' },
      { status: 500 }
    );
  }
}
