/**
 * AI-Generated Code Detection for ShitCode Shield
 *
 * Heuristics to detect AI-generated code in a diff.
 * Returns confidence levels and signal lists per file.
 */

export interface AIDetectionResult {
  file: string;
  isAiGenerated: boolean;
  confidence: 'high' | 'medium' | 'low';
  signals: string[];
}

/** Parsed file from a unified diff */
interface DiffFile {
  filename: string;
  addedLines: string[];
  totalAddedLines: number;
}

/**
 * Parse a unified diff string into per-file added lines.
 */
export function parseDiff(diff: string): DiffFile[] {
  const files: DiffFile[] = [];
  let currentFile: DiffFile | null = null;

  const lines = diff.split('\n');
  for (const line of lines) {
    // Detect file header: diff --git a/path b/path
    const fileMatch = line.match(/^diff --git a\/(.*) b\/(.*)$/);
    if (fileMatch) {
      if (currentFile) {
        files.push(currentFile);
      }
      currentFile = {
        filename: fileMatch[2],
        addedLines: [],
        totalAddedLines: 0,
      };
      continue;
    }

    // Detect new file: --- /dev/null
    if (line.startsWith('--- /dev/null') && currentFile) {
      continue;
    }

    // Added lines start with +
    if (line.startsWith('+') && !line.startsWith('+++') && currentFile) {
      currentFile.addedLines.push(line.slice(1));
      currentFile.totalAddedLines++;
    }
  }

  if (currentFile) {
    files.push(currentFile);
  }

  return files;
}

/**
 * AI marker comment patterns.
 */
const AI_COMMENT_PATTERNS: RegExp[] = [
  /\/\/\s*generated by/i,
  /\/\/\s*ai\b/i,
  /\/\/\s*copilot/i,
  /\/\/\s*claude/i,
  /\/\/\s*gpt\b/i,
  /\/\/\s*chatgpt/i,
  /#\s*generated by ai/i,
  /#\s*ai-generated/i,
  /<!--\s*ai\s*generated\s*-->/i,
  /\*\s*generated by ai/i,
  /\/\/\s*this (?:code|function|file) (?:was )?generated/i,
  /\/\/\s*auto-?generated/i,
  /\/\/\s*created (?:by|with) (?:an? )?(?:ai|llm|claude|gpt|copilot|chatgpt)/i,
];

/**
 * Check if a file's content has AI marker comments.
 */
function detectAIComments(lines: string[]): string[] {
  const signals: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('//') || trimmed.startsWith('#') || trimmed.startsWith('*') || trimmed.startsWith('<!--')) {
      for (const pattern of AI_COMMENT_PATTERNS) {
        if (pattern.test(trimmed)) {
          const matchedLabel = trimmed.length > 60 ? trimmed.slice(0, 57) + '...' : trimmed;
          signals.push(`AI comment: "${matchedLabel}"`);
          break;
        }
      }
    }
  }

  return [...new Set(signals)];
}

/**
 * Calculate comment-to-code ratio.
 */
function calculateCommentRatio(lines: string[]): { ratio: number; commentLines: number; codeLines: number } {
  let commentLines = 0;
  let codeLines = 0;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    if (
      trimmed.startsWith('//') ||
      trimmed.startsWith('#') ||
      trimmed.startsWith('*') ||
      trimmed.startsWith('/*') ||
      trimmed.startsWith('*') ||
      trimmed.startsWith('<!--')
    ) {
      commentLines++;
    } else {
      codeLines++;
    }
  }

  const total = commentLines + codeLines;
  const ratio = total > 0 ? commentLines / total : 0;

  return { ratio, commentLines, codeLines };
}

/**
 * Check if every function has complete JSDoc/docstring.
 */
function detectPerfectJSDoc(lines: string[]): boolean {
  const codeLines = lines.filter((l) => {
    const t = l.trim();
    return t.length > 0 && !t.startsWith('//') && !t.startsWith('#') && !t.startsWith('*') && !t.startsWith('/*');
  });

  // Find function declarations
  const funcPattern = /(?:function\s+\w+|(?:const|let|var)\s+\w+\s*=\s*(?:async\s+)?(?:\([^)]*\)|[\w]+)\s*=>|export\s+(?:default\s+)?function\s+\w+|async\s+function\s+\w+|\w+\s*\([^)]*\)\s*\{)/;
  const funcLines = codeLines.filter((l) => funcPattern.test(l));

  if (funcLines.length < 3) return false;

  // Check if most functions have JSDoc before them
  let withJSDoc = 0;
  for (let i = 0; i < lines.length; i++) {
    if (!funcPattern.test(lines[i])) continue;
    // Look backwards for JSDoc
    let foundJSDoc = false;
    for (let j = i - 1; j >= Math.max(0, i - 5); j--) {
      const prev = lines[j].trim();
      if (prev.startsWith('/**') || prev.startsWith('* @')) {
        foundJSDoc = true;
        break;
      }
      if (prev === '' || prev === '}' || prev === ');') continue;
      break;
    }
    if (foundJSDoc) withJSDoc++;
  }

  // If 90%+ of functions have JSDoc, it's suspicious
  return funcLines.length > 0 && (withJSDoc / funcLines.length) >= 0.9;
}

/**
 * Check if imports are perfectly alphabetized.
 */
function detectAlphabetizedImports(lines: string[]): boolean {
  const imports: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.match(/^(import |from |require\()/)) {
      imports.push(trimmed);
    }
  }

  if (imports.length < 4) return false;

  const sorted = [...imports].sort((a, b) => a.localeCompare(b));
  return imports.every((imp, i) => imp === sorted[i]);
}

/**
 * Check for absence of TODO/FIXME/HACK comments.
 */
function detectNoTodos(lines: string[]): boolean {
  const codeLines = lines.filter((l) => {
    const t = l.trim();
    return t.length > 0 && !t.startsWith('//') && !t.startsWith('#') && !t.startsWith('*');
  });

  if (codeLines.length < 20) return false;

  const hasTodo = lines.some((l) => {
    const t = l.toLowerCase();
    return (
      t.includes('todo') ||
      t.includes('fixme') ||
      t.includes('hack') ||
      t.includes('xxx') ||
      t.includes('noqa')
    );
  });

  return !hasTodo;
}

/**
 * Check for consistent formatting (no mixed tabs/spaces).
 */
function detectPerfectFormatting(lines: string[]): boolean {
  let hasTabs = false;
  let hasSpaces = false;
  let indentedLines = 0;

  for (const line of lines) {
    if (line.startsWith('\t')) hasTabs = true;
    if (line.startsWith('  ')) hasSpaces = true;
    if (line.startsWith('\t') || line.startsWith('  ')) indentedLines++;
  }

  // Mixed tabs and spaces = not perfect
  if (hasTabs && hasSpaces) return false;
  if (indentedLines < 10) return false;

  return true;
}

/**
 * Detect AI-generated code characteristics for a single file.
 */
function analyzeFile(file: DiffFile): AIDetectionResult {
  const signals: string[] = [];
  const { addedLines, totalAddedLines } = file;

  if (addedLines.length === 0) {
    return { file: file.filename, isAiGenerated: false, confidence: 'low', signals: [] };
  }

  // 1. AI marker comments
  const aiComments = detectAIComments(addedLines);
  if (aiComments.length > 0) {
    signals.push(...aiComments);
  }

  // 2. High comment-to-code ratio (>40%)
  const { ratio } = calculateCommentRatio(addedLines);
  if (ratio > 0.4) {
    signals.push(`High comment ratio (${(ratio * 100).toFixed(0)}% comments)`);
  }

  // 3. Perfect JSDoc on every function
  if (detectPerfectJSDoc(addedLines)) {
    signals.push('Perfect JSDoc on all functions');
  }

  // 4. Alphabetized imports
  if (detectAlphabetizedImports(addedLines)) {
    signals.push('Imports perfectly alphabetized');
  }

  // 5. No TODO/FIXME/HACK comments
  if (detectNoTodos(addedLines)) {
    signals.push('No TODO/FIXME/HACK comments');
  }

  // 6. Perfect formatting (consistent tabs or spaces)
  if (detectPerfectFormatting(addedLines)) {
    signals.push('Perfectly consistent formatting');
  }

  // 7. Large file added in single commit (100+ lines)
  if (totalAddedLines >= 100) {
    signals.push(`${totalAddedLines} lines added in single commit`);
  }

  // Determine confidence
  let confidence: 'high' | 'medium' | 'low';
  if (signals.length >= 4) {
    confidence = 'high';
  } else if (signals.length >= 2) {
    confidence = 'medium';
  } else {
    confidence = 'low';
  }

  // AI comment is a strong signal on its own
  if (aiComments.length > 0 && confidence === 'low') {
    confidence = 'medium';
  }

  return {
    file: file.filename,
    isAiGenerated: signals.length >= 2,
    confidence,
    signals,
  };
}

/**
 * Detect AI-generated code in a PR diff.
 *
 * @param diff - The unified diff string from the PR
 * @param ignorePatterns - Glob patterns to skip
 * @returns Array of AI detection results per file
 */
export function detectAIGeneratedCode(
  diff: string,
  ignorePatterns: string[] = []
): AIDetectionResult[] {
  const files = parseDiff(diff);
  const results: AIDetectionResult[] = [];

  for (const file of files) {
    // Skip ignored files
    if (shouldIgnore(file.filename, ignorePatterns)) {
      continue;
    }

    // Skip non-code files
    if (isNonCodeFile(file.filename)) {
      continue;
    }

    results.push(analyzeFile(file));
  }

  return results;
}

/**
 * Check if a filename matches any ignore pattern.
 * Supports simple glob patterns (*, **, ?).
 */
export function shouldIgnore(filename: string, patterns: string[]): boolean {
  for (const pattern of patterns) {
    if (matchGlob(filename, pattern)) {
      return true;
    }
  }
  return false;
}

/**
 * Simple glob matcher for ignore patterns.
 */
function matchGlob(filename: string, pattern: string): boolean {
  const normalized = pattern.trim();
  if (!normalized || normalized.startsWith('#')) return false;

  // Convert glob to regex
  const regexStr = normalized
    .replace(/[.+^${}()|[\]\\]/g, '\\$&')
    .replace(/\*/g, '.*')
    .replace(/\?/g, '.');

  const regex = new RegExp(`^${regexStr}$`, 'i');
  return regex.test(filename);
}

/**
 * Check if a file is a non-code file (images, binaries, etc.)
 */
function isNonCodeFile(filename: string): boolean {
  const nonCodeExtensions = [
    '.png', '.jpg', '.jpeg', '.gif', '.svg', '.ico', '.webp', '.bmp',
    '.mp4', '.mp3', '.wav', '.ogg', '.pdf', '.zip', '.tar', '.gz',
    '.woff', '.woff2', '.ttf', '.eot', '.otf',
    '.lock', '.log', '.map',
  ];

  const lower = filename.toLowerCase();
  return nonCodeExtensions.some((ext) => lower.endsWith(ext));
}

/**
 * Parse .vibesec-ignore content into ignore patterns.
 *
 * @param content - Raw content of .vibesec-ignore file
 * @returns Array of glob patterns
 */
export function parseIgnoreFile(content: string): string[] {
  return content
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith('#'));
}
