'use client';

import { useState, useCallback, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Palette,
  Globe,
  FileText,
  LogIn,
  Settings,
  Eye,
  Save,
  RotateCcw,
  Download,
  Upload,
  ChevronDown,
  ChevronRight,
  Copy,
  Check,
  ExternalLink,
  Monitor,
  Moon,
  Sun,
  Zap,
  Shield,
  Mail,
  Server,
  Code2,
  CheckCircle2,
  Clock,
  AlertTriangle,
  Sparkles,
  Layout,
  Image as ImageIcon,
  Type,
  ScanLine,
  Columns2,
  RectangleHorizontal,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from '@/components/ui/collapsible';

// ── Types ────────────────────────────────────────────────────────────────────

interface BrandConfig {
  companyName: string;
  productName: string;
  primaryColor: string;
  accentColor: string;
  logoText: string;
  faviconUrl: string;
  customDomain: string;
  loginPageMessage: string;
  reportHeader: string;
  reportFooter: string;
  hidePoweredBy: boolean;
  customCss: string;
  emailFromName: string;
  emailFromAddress: string;
  darkMode: boolean;
  theme: 'dark' | 'light' | 'auto';
}

interface WhiteLabelPanelProps {
  currentBranding?: BrandConfig;
  onSave?: (config: BrandConfig) => void;
}

// ── Defaults ──────────────────────────────────────────────────────────────────

const DEFAULT_CONFIG: BrandConfig = {
  companyName: 'Acme Security',
  productName: 'ReconPro',
  primaryColor: '#00ff88',
  accentColor: '#0a0d14',
  logoText: 'RP',
  faviconUrl: '',
  customDomain: '',
  loginPageMessage: 'Welcome to the Attack Surface Management Platform. Enter your credentials to continue.',
  reportHeader: 'Confidential — Attack Surface Report',
  reportFooter: 'Generated by Acme Security ReconPro',
  hidePoweredBy: true,
  customCss: '',
  emailFromName: 'Acme Security',
  emailFromAddress: 'noreply@acme-security.com',
  darkMode: true,
  theme: 'dark',
};

interface ColorPalette {
  name: string;
  primary: string;
  accent: string;
}

const PRESET_PALETTES: ColorPalette[] = [
  { name: 'Midnight', primary: '#00ff88', accent: '#0a0d14' },
  { name: 'Ocean', primary: '#06b6d4', accent: '#0c1222' },
  { name: 'Crimson', primary: '#ff3355', accent: '#1a0a0a' },
  { name: 'Royal', primary: '#a78bfa', accent: '#0f0a1e' },
  { name: 'Solar', primary: '#ff8844', accent: '#1a1008' },
  { name: 'Forest', primary: '#22c55e', accent: '#0a1a0a' },
];

interface DnsRecord {
  type: 'CNAME' | 'TXT' | 'A';
  name: string;
  value: string;
  status: 'verified' | 'pending';
}

const DNS_RECORDS: DnsRecord[] = [
  {
    type: 'CNAME',
    name: 'portal.yourcompany.com',
    value: 'reconpro.acmecorp.io',
    status: 'verified',
  },
  {
    type: 'TXT',
    name: 'yourcompany.com',
    value: 'v=spf1 include:reconpro.acmecorp.io ~all',
    status: 'pending',
  },
  {
    type: 'A',
    name: 'portal.yourcompany.com',
    value: '35.190.42.117',
    status: 'verified',
  },
];

// ── Animation Variants ──────────────────────────────────────────────────────

const fadeInUp = {
  initial: { opacity: 0, y: 12 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.35, ease: 'easeOut' as const },
};

const staggerContainer = {
  animate: { transition: { staggerChildren: 0.06 } },
};

// ── Shared Glass Card ────────────────────────────────────────────────────────

function GlassCard({
  children,
  className = '',
  delay = 0,
}: {
  children: React.ReactNode;
  className?: string;
  delay?: number;
}) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4, delay, ease: 'easeOut' as const }}
      className={`rounded-2xl border border-white/[0.06] bg-[#080b14]/80 backdrop-blur-xl ${className}`}
    >
      {children}
    </motion.div>
  );
}

function SectionHeader({
  icon,
  title,
  description,
}: {
  icon: React.ReactNode;
  title: string;
  description?: string;
}) {
  return (
    <div className="flex items-start gap-3 mb-6">
      <div
        className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg"
        style={{ backgroundColor: 'rgba(52,211,153,0.1)', color: '#00ff88' }}
      >
        {icon}
      </div>
      <div>
        <h3 className="text-[15px] font-semibold text-[#f0f0f0]">{title}</h3>
        {description && (
          <p className="text-[13px] text-[#444444] mt-0.5">{description}</p>
        )}
      </div>
    </div>
  );
}

// ── Color Swatches ──────────────────────────────────────────────────────────

function ColorSwatch({
  color,
  selected,
  onClick,
  size = 28,
}: {
  color: string;
  selected: boolean;
  onClick: () => void;
  size?: number;
}) {
  return (
    <button
      onClick={onClick}
      className="relative rounded-lg transition-all duration-200 hover:scale-110 focus:outline-none"
      style={{ width: size, height: size, backgroundColor: color }}
    >
      {selected && (
        <motion.div
          initial={{ scale: 0 }}
          animate={{ scale: 1 }}
          className="absolute inset-0 flex items-center justify-center rounded-lg ring-2 ring-white ring-offset-2 ring-offset-[#080a10]"
        >
          <Check className="h-3.5 w-3.5 text-white drop-shadow-sm" />
        </motion.div>
      )}
    </button>
  );
}

// ── Color Picker ─────────────────────────────────────────────────────────────

function ColorPickerField({
  label,
  value,
  onChange,
  presets,
}: {
  label: string;
  value: string;
  onChange: (v: string) => void;
  presets: string[];
}) {
  const [hexInput, setHexInput] = useState(value);
  const handleHexSubmit = () => {
    if (/^#[0-9a-fA-F]{6}$/.test(hexInput)) {
      onChange(hexInput);
    }
  };
  return (
    <div className="space-y-2.5">
      <Label className="text-[13px] font-medium text-[#444444]">{label}</Label>
      <div className="flex items-center gap-3">
        <div className="relative">
          <div
            className="h-10 w-10 rounded-lg border border-white/10 shadow-inner cursor-pointer"
            style={{ backgroundColor: value }}
          />
        </div>
        <div className="flex-1 flex items-center gap-2">
          <Input
            value={hexInput}
            onChange={(e) => setHexInput(e.target.value)}
            onBlur={() => setHexInput(value)}
            onKeyDown={(e) => e.key === 'Enter' && handleHexSubmit()}
            className="h-10 bg-[#000000] border-white/[0.08] text-[#f0f0f0] font-mono text-sm placeholder:text-[#333333]"
            placeholder="#00ff88"
          />
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="h-10 border-white/[0.08] text-[#444444] hover:text-[#f0f0f0] hover:bg-white/[0.04] shrink-0"
            onClick={handleHexSubmit}
          >
            Apply
          </Button>
        </div>
      </div>
      <div className="flex items-center gap-2 flex-wrap">
        {presets.map((p) => (
          <ColorSwatch
            key={p}
            color={p}
            selected={p.toLowerCase() === value.toLowerCase()}
            onClick={() => {
              onChange(p);
              setHexInput(p);
            }}
          />
        ))}
      </div>
    </div>
  );
}

// ── DNS Record Row ──────────────────────────────────────────────────────────

function DnsRecordRow({ record }: { record: DnsRecord }) {
  const [copied, setCopied] = useState(false);
  const handleCopy = () => {
    navigator.clipboard.writeText(record.value);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };
  return (
    <div className="flex items-center gap-3 rounded-xl bg-[#030407]/60 border border-white/[0.04] p-3">
      <Badge
        variant="outline"
        className="shrink-0 font-mono text-xs px-2 py-0.5 border-[#00ff88]/30 text-[#00ff88] bg-[#00ff88]/5"
      >
        {record.type}
      </Badge>
      <div className="flex-1 min-w-0">
        <p className="text-[13px] font-medium text-[#f0f0f0] truncate">
          {record.name}
        </p>
        <p className="text-xs text-[#444444] font-mono truncate">
          {record.value}
        </p>
      </div>
      <div className="flex items-center gap-2 shrink-0">
        {record.status === 'verified' ? (
          <Badge className="bg-[#00ff88]/10 text-[#00ff88] border-[#00ff88]/20 text-xs px-2 py-0.5">
            <CheckCircle2 className="h-3 w-3 mr-1" />
            Verified
          </Badge>
        ) : (
          <Badge className="bg-yellow-500/10 text-yellow-400 border-yellow-500/20 text-xs px-2 py-0.5">
            <Clock className="h-3 w-3 mr-1" />
            Pending
          </Badge>
        )}
        <Button
          variant="ghost"
          size="sm"
          className="h-8 w-8 p-0 text-[#444444] hover:text-[#f0f0f0] hover:bg-white/[0.06]"
          onClick={handleCopy}
        >
          {copied ? (
            <Check className="h-3.5 w-3.5 text-[#00ff88]" />
          ) : (
            <Copy className="h-3.5 w-3.5" />
          )}
        </Button>
      </div>
    </div>
  );
}

// ── Live Preview Panel ───────────────────────────────────────────────────────

function LivePreview({ config }: { config: BrandConfig }) {
  return (
    <div
      className="rounded-xl border border-white/[0.06] overflow-hidden"
      style={{ backgroundColor: config.accentColor || '#0a0d14' }}
    >
      {/* Mock nav bar */}
      <div className="flex items-center gap-2 px-4 py-2.5 border-b border-white/[0.06]">
        <div
          className="flex h-7 w-7 items-center justify-center rounded-md text-xs font-bold text-[#080a10]"
          style={{ backgroundColor: config.primaryColor }}
        >
          {config.logoText || 'RP'}
        </div>
        <span
          className="text-sm font-semibold"
          style={{ color: config.primaryColor }}
        >
          {config.productName || 'ReconPro'}
        </span>
        <div className="ml-auto flex items-center gap-3">
          {['Dashboard', 'Scans', 'Reports'].map((item) => (
            <span
              key={item}
              className="text-[11px] text-[#444444] hover:text-[#f0f0f0] transition-colors cursor-default"
            >
              {item}
            </span>
          ))}
        </div>
      </div>
      {/* Mock content area */}
      <div className="p-4 space-y-3">
        <div className="flex items-center gap-2">
          <div
            className="h-1.5 w-1.5 rounded-full animate-pulse"
            style={{ backgroundColor: config.primaryColor }}
          />
          <span className="text-[11px] text-[#444444]">Live Preview</span>
        </div>
        {/* Mock stat cards */}
        <div className="grid grid-cols-3 gap-2">
          {['256 Hosts', '12 Risks', '99% Uptime'].map((label, i) => (
            <div
              key={label}
              className="rounded-lg border border-white/[0.06] bg-white/[0.02] p-2 text-center"
            >
              <div
                className="text-xs font-semibold"
                style={{ color: config.primaryColor }}
              >
                {label.split(' ')[0]}
              </div>
              <div className="text-[10px] text-[#333333]">
                {label.split(' ').slice(1).join(' ')}
              </div>
            </div>
          ))}
        </div>
        {/* Report header sample */}
        <div className="rounded-lg border border-white/[0.06] bg-white/[0.02] p-2.5">
          <p className="text-[10px] text-[#333333] mb-1">Report Header</p>
          <p className="text-[11px] font-medium text-[#f0f0f0]">
            {config.reportHeader || 'Confidential — Attack Surface Report'}
          </p>
          {!config.hidePoweredBy && (
            <p className="text-[9px] text-[#333333] mt-1">
              Powered by ReconPro
            </p>
          )}
        </div>
      </div>
    </div>
  );
}

// ── Full Preview Modal ───────────────────────────────────────────────────────

function FullPreviewModal({ config }: { config: BrandConfig }) {
  return (
    <div
      className="rounded-2xl overflow-hidden border border-white/[0.06] mx-auto"
      style={{ backgroundColor: config.accentColor || '#0a0d14', maxWidth: 720 }}
    >
      {/* Sidebar mock */}
      <div className="flex min-h-[440px]">
        {/* Sidebar */}
        <div className="w-44 border-r border-white/[0.06] p-3 space-y-1">
          <div className="flex items-center gap-2 mb-5 px-1">
            <div
              className="flex h-7 w-7 items-center justify-center rounded-md text-xs font-bold text-[#080a10]"
              style={{ backgroundColor: config.primaryColor }}
            >
              {config.logoText || 'RP'}
            </div>
            <span
              className="text-xs font-bold truncate"
              style={{ color: config.primaryColor }}
            >
              {config.productName}
            </span>
          </div>
          {[
            { icon: <Monitor className="h-3.5 w-3.5" />, label: 'Dashboard', active: true },
            { icon: <ScanLine className="h-3.5 w-3.5" />, label: 'Scans' },
            { icon: <Shield className="h-3.5 w-3.5" />, label: 'Security' },
            { icon: <FileText className="h-3.5 w-3.5" />, label: 'Reports' },
            { icon: <Settings className="h-3.5 w-3.5" />, label: 'Settings' },
          ].map((item) => (
            <div
              key={item.label}
              className={`flex items-center gap-2 rounded-lg px-2.5 py-1.5 text-[11px] cursor-default ${
                item.active
                  ? 'text-white'
                  : 'text-[#444444] hover:text-[#f0f0f0]'
              }`}
              style={
                item.active
                  ? { backgroundColor: `${config.primaryColor}20`, color: config.primaryColor }
                  : undefined
              }
            >
              {item.icon}
              {item.label}
            </div>
          ))}
        </div>
        {/* Main content mock */}
        <div className="flex-1 p-5 space-y-4">
          {/* Title bar */}
          <div className="flex items-center justify-between">
            <div>
              <h2 className="text-sm font-semibold text-[#f0f0f0]">Dashboard</h2>
              <p className="text-[11px] text-[#444444]">Welcome back to {config.companyName}</p>
            </div>
            <div
              className="h-7 rounded-lg px-3 flex items-center text-[11px] font-medium text-[#080a10]"
              style={{ backgroundColor: config.primaryColor }}
            >
              New Scan
            </div>
          </div>
          {/* Stat grid */}
          <div className="grid grid-cols-3 gap-3">
            {[
              { label: 'Total Assets', val: '1,284' },
              { label: 'Critical Risks', val: '7' },
              { label: 'Open Ports', val: '3,421' },
            ].map((s) => (
              <div
                key={s.label}
                className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-3"
              >
                <p className="text-[10px] text-[#444444]">{s.label}</p>
                <p
                  className="text-lg font-bold mt-0.5"
                  style={{ color: config.primaryColor }}
                >
                  {s.val}
                </p>
              </div>
            ))}
          </div>
          {/* Activity area */}
          <div className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-3">
            <p className="text-[11px] font-medium text-[#f0f0f0] mb-2">Recent Activity</p>
            {[
              'Scan completed for acme-corp.com',
              'New subdomain discovered: staging.acme-corp.com',
              'SSL certificate expiring in 14 days',
            ].map((line, i) => (
              <div
                key={i}
                className="flex items-center gap-2 py-1.5 border-t border-white/[0.04] first:border-0"
              >
                <div
                  className="h-1.5 w-1.5 rounded-full shrink-0"
                  style={{
                    backgroundColor:
                      i === 0 ? '#00ff88' : i === 1 ? config.primaryColor : '#ff8844',
                  }}
                />
                <span className="text-[11px] text-[#444444]">{line}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

// ── Login Style Cards ────────────────────────────────────────────────────────

function LoginStyleCard({
  name,
  primaryColor,
  selected,
  onClick,
  children,
}: {
  name: string;
  primaryColor: string;
  selected: boolean;
  onClick: () => void;
  children: React.ReactNode;
}) {
  return (
    <motion.button
      whileHover={{ scale: 1.02 }}
      whileTap={{ scale: 0.98 }}
      onClick={onClick}
      className={`relative flex flex-col items-center gap-2 rounded-xl border-2 p-3 transition-all cursor-pointer ${
        selected
          ? 'border-[#00ff88]/40 bg-[#00ff88]/5'
          : 'border-white/[0.06] bg-white/[0.02] hover:border-white/[0.12]'
      }`}
    >
      {children}
      <span className="text-xs font-medium text-[#f0f0f0]">{name}</span>
      {selected && (
        <motion.div
          initial={{ scale: 0 }}
          animate={{ scale: 1 }}
          className="absolute -top-1.5 -right-1.5 flex h-4 w-4 items-center justify-center rounded-full"
          style={{ backgroundColor: primaryColor }}
        >
          <Check className="h-2.5 w-2.5 text-[#080a10]" />
        </motion.div>
      )}
    </motion.button>
  );
}

// ── Main Component ──────────────────────────────────────────────────────────

export function WhiteLabelPanel({
  currentBranding,
  onSave,
}: WhiteLabelPanelProps) {
  const [config, setConfig] = useState<BrandConfig>(
    currentBranding ? { ...DEFAULT_CONFIG, ...currentBranding } : { ...DEFAULT_CONFIG },
  );
  const [advancedOpen, setAdvancedOpen] = useState(false);
  const [dnsOpen, setDnsOpen] = useState(false);
  const [previewOpen, setPreviewOpen] = useState(false);
  const [loginStyle, setLoginStyle] = useState<'default' | 'centered' | 'split'>('default');
  const [saved, setSaved] = useState(false);
  const [hasChanges, setHasChanges] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const update = useCallback(
    <K extends keyof BrandConfig>(key: K, val: BrandConfig[K]) => {
      setConfig((prev) => ({ ...prev, [key]: val }));
      setHasChanges(true);
      setSaved(false);
    },
    [],
  );

  const handleSave = () => {
    onSave?.(config);
    setSaved(true);
    setHasChanges(false);
    setTimeout(() => setSaved(false), 3000);
  };

  const handleReset = () => {
    setConfig({ ...DEFAULT_CONFIG });
    setHasChanges(false);
    setSaved(false);
  };

  const handleExport = () => {
    const blob = new Blob([JSON.stringify(config, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `reconpro-brand-config-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleImport = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (ev) => {
      try {
        const data = JSON.parse(ev.target?.result as string);
        setConfig((prev) => ({ ...prev, ...data }));
        setHasChanges(true);
      } catch {
        // Invalid JSON
      }
    };
    reader.readAsText(file);
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  const applyPalette = (palette: ColorPalette) => {
    setConfig((prev) => ({
      ...prev,
      primaryColor: palette.primary,
      accentColor: palette.accent,
    }));
    setHasChanges(true);
    setSaved(false);
  };

  return (
    <div className="min-h-screen bg-[#030407] text-[#f0f0f0]">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-8 pb-24">
        {/* ── 1. Header ─────────────────────────────────────────────────── */}
        <motion.div {...fadeInUp} className="mb-8">
          <div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-4">
            <div>
              <div className="flex items-center gap-2.5 mb-2">
                <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#00ff88]/10">
                  <Sparkles className="h-4 w-4 text-[#00ff88]" />
                </div>
                <h1 className="text-2xl font-bold tracking-tight text-[#f0f0f0]">
                  White-Label Branding
                </h1>
              </div>
              <p className="text-sm text-[#444444] max-w-xl">
                Customize every aspect of ReconPro to match your brand identity. Changes will be
                reflected across login pages, reports, emails, and the full application interface.
              </p>
            </div>
            <div className="flex items-center gap-2.5 flex-wrap">
              <Dialog open={previewOpen} onOpenChange={setPreviewOpen}>
                <DialogTrigger asChild>
                  <Button
                    variant="outline"
                    className="border-[#00ff88]/20 text-[#00ff88] hover:bg-[#00ff88]/10 hover:text-[#00ff88] gap-1.5"
                  >
                    <Eye className="h-3.5 w-3.5" />
                    Preview Changes
                  </Button>
                </DialogTrigger>
                <DialogContent className="bg-[#080b14] border-white/[0.08] text-[#f0f0f0] sm:max-w-4xl max-h-[85vh] overflow-y-auto">
                  <DialogHeader>
                    <DialogTitle className="text-[#f0f0f0] flex items-center gap-2">
                      <Monitor className="h-4 w-4 text-[#00ff88]" />
                      Full Preview
                    </DialogTitle>
                  </DialogHeader>
                  <FullPreviewModal config={config} />
                </DialogContent>
              </Dialog>
              <Button
                variant="outline"
                className="border-white/[0.08] text-[#444444] hover:text-[#f0f0f0] hover:bg-white/[0.04] gap-1.5"
                onClick={handleReset}
              >
                <RotateCcw className="h-3.5 w-3.5" />
                Reset to Default
              </Button>
              <Button
                className="bg-[#00ff88] text-[#080a10] hover:bg-[#00ff88]/90 font-semibold gap-1.5"
                onClick={handleSave}
              >
                <Save className="h-3.5 w-3.5" />
                {saved ? 'Saved!' : 'Save Configuration'}
              </Button>
            </div>
          </div>
        </motion.div>

        {/* ── Main Layout ───────────────────────────────────────────────── */}
        <div className="grid grid-cols-1 xl:grid-cols-[1fr_340px] gap-6">
          <motion.div
            className="space-y-6"
            variants={staggerContainer}
            initial="initial"
            animate="animate"
          >
            {/* ── 2. Live Preview Panel (top on mobile, sidebar on desktop is above) ── */}
            {/* The live preview is shown in the right column on xl screens */}
            {/* On smaller screens it appears at the top */}
            <div className="xl:hidden">
              <GlassCard className="p-5" delay={0.02}>
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-2">
                    <Monitor className="h-4 w-4 text-[#00ff88]" />
                    <h3 className="text-sm font-semibold text-[#f0f0f0]">Live Preview</h3>
                    <Badge className="bg-[#00ff88]/10 text-[#00ff88] border-[#00ff88]/20 text-[10px] px-1.5 py-0">
                      REAL-TIME
                    </Badge>
                  </div>
                  <Dialog open={previewOpen} onOpenChange={setPreviewOpen}>
                    <DialogTrigger asChild>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-7 text-[11px] text-[#444444] hover:text-[#00ff88] gap-1"
                      >
                        <ExternalLink className="h-3 w-3" />
                        Full Preview
                      </Button>
                    </DialogTrigger>
                    <DialogContent className="bg-[#080b14] border-white/[0.08] text-[#f0f0f0] sm:max-w-4xl max-h-[85vh] overflow-y-auto">
                      <DialogHeader>
                        <DialogTitle className="text-[#f0f0f0] flex items-center gap-2">
                          <Monitor className="h-4 w-4 text-[#00ff88]" />
                          Full Preview
                        </DialogTitle>
                      </DialogHeader>
                      <FullPreviewModal config={config} />
                    </DialogContent>
                  </Dialog>
                </div>
                <LivePreview config={config} />
              </GlassCard>
            </div>

            {/* ── 3. Brand Identity Section ───────────────────────────── */}
            <GlassCard className="p-6" delay={0.04}>
              <SectionHeader
                icon={<Palette className="h-4 w-4" />}
                title="Brand Identity"
                description="Core brand elements — logo, colors, and naming"
              />
              <div className="space-y-5">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label className="text-[13px] font-medium text-[#444444]">
                      Company Name
                    </Label>
                    <Input
                      value={config.companyName}
                      onChange={(e) => update('companyName', e.target.value)}
                      className="h-10 bg-[#000000] border-white/[0.08] text-[#f0f0f0] placeholder:text-[#333333]"
                      placeholder="Acme Security"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label className="text-[13px] font-medium text-[#444444]">
                      Product Name
                    </Label>
                    <Input
                      value={config.productName}
                      onChange={(e) => update('productName', e.target.value)}
                      className="h-10 bg-[#000000] border-white/[0.08] text-[#f0f0f0] placeholder:text-[#333333]"
                      placeholder="ReconPro"
                    />
                  </div>
                </div>

                <div className="space-y-2">
                  <Label className="text-[13px] font-medium text-[#444444]">
                    Logo Text (shown in sidebar)
                  </Label>
                  <Input
                    value={config.logoText}
                    onChange={(e) => update('logoText', e.target.value)}
                    className="h-10 bg-[#000000] border-white/[0.08] text-[#f0f0f0] placeholder:text-[#333333] max-w-xs"
                    placeholder="RP"
                  />
                  <p className="text-[11px] text-[#333333]">
                    Short text or initials displayed in the navigation sidebar
                  </p>
                </div>

                <Separator className="bg-white/[0.06]" />

                {/* Color pickers */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                  <ColorPickerField
                    label="Primary Color"
                    value={config.primaryColor}
                    onChange={(v) => update('primaryColor', v)}
                    presets={['#00ff88', '#06b6d4', '#ff3355', '#a78bfa', '#ff8844', '#22c55e', '#ec4899', '#14b8a6']}
                  />
                  <ColorPickerField
                    label="Accent Color"
                    value={config.accentColor}
                    onChange={(v) => update('accentColor', v)}
                    presets={['#0a0d14', '#0c1222', '#1a0a0a', '#0f0a1e', '#1a1008', '#0a1a0a', '#0d0a18', '#0a1418']}
                  />
                </div>

                {/* Preset Palettes */}
                <div className="space-y-2.5">
                  <Label className="text-[13px] font-medium text-[#444444]">
                    Preset Palettes
                  </Label>
                  <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2.5">
                    {PRESET_PALETTES.map((palette) => (
                      <motion.button
                        key={palette.name}
                        whileHover={{ scale: 1.04 }}
                        whileTap={{ scale: 0.97 }}
                        onClick={() => applyPalette(palette)}
                        className={`relative flex flex-col items-center gap-2 rounded-xl border-2 p-3 transition-all cursor-pointer ${
                          config.primaryColor.toLowerCase() === palette.primary.toLowerCase() &&
                          config.accentColor.toLowerCase() === palette.accent.toLowerCase()
                            ? 'border-[#00ff88]/40 bg-[#00ff88]/5'
                            : 'border-white/[0.06] bg-white/[0.02] hover:border-white/[0.12]'
                        }`}
                      >
                        <div className="flex items-center gap-1">
                          <div
                            className="h-5 w-5 rounded-full border border-white/10"
                            style={{ backgroundColor: palette.primary }}
                          />
                          <div
                            className="h-5 w-5 rounded-full border border-white/10"
                            style={{ backgroundColor: palette.accent }}
                          />
                        </div>
                        <span className="text-[11px] font-medium text-[#444444]">
                          {palette.name}
                        </span>
                        {config.primaryColor.toLowerCase() === palette.primary.toLowerCase() &&
                          config.accentColor.toLowerCase() === palette.accent.toLowerCase() && (
                            <Check className="absolute top-1.5 right-1.5 h-3 w-3 text-[#00ff88]" />
                          )}
                      </motion.button>
                    ))}
                  </div>
                </div>
              </div>
            </GlassCard>

            {/* ── 4. Domain & Email Section ─────────────────────────────── */}
            <GlassCard className="p-6" delay={0.06}>
              <SectionHeader
                icon={<Globe className="h-4 w-4" />}
                title="Domain & Email"
                description="Custom domain setup and email sender configuration"
              />
              <div className="space-y-5">
                <div className="space-y-2">
                  <Label className="text-[13px] font-medium text-[#444444] flex items-center gap-1.5">
                    <Server className="h-3 w-3" />
                    Custom Domain
                  </Label>
                  <Input
                    value={config.customDomain}
                    onChange={(e) => update('customDomain', e.target.value)}
                    className="h-10 bg-[#000000] border-white/[0.08] text-[#f0f0f0] placeholder:text-[#333333]"
                    placeholder="portal.yourcompany.com"
                  />
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label className="text-[13px] font-medium text-[#444444] flex items-center gap-1.5">
                      <Mail className="h-3 w-3" />
                      Email From Name
                    </Label>
                    <Input
                      value={config.emailFromName}
                      onChange={(e) => update('emailFromName', e.target.value)}
                      className="h-10 bg-[#000000] border-white/[0.08] text-[#f0f0f0] placeholder:text-[#333333]"
                      placeholder="Acme Security"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label className="text-[13px] font-medium text-[#444444] flex items-center gap-1.5">
                      <Mail className="h-3 w-3" />
                      Email From Address
                    </Label>
                    <Input
                      value={config.emailFromAddress}
                      onChange={(e) => update('emailFromAddress', e.target.value)}
                      className="h-10 bg-[#000000] border-white/[0.08] text-[#f0f0f0] placeholder:text-[#333333]"
                      placeholder="noreply@acme-security.com"
                    />
                  </div>
                </div>

                {/* DNS Config helper */}
                <Collapsible open={dnsOpen} onOpenChange={setDnsOpen}>
                  <CollapsibleTrigger asChild>
                    <button className="flex items-center gap-2 text-[13px] font-medium text-[#00ff88] hover:text-[#00ff88]/80 transition-colors cursor-pointer w-full">
                      <Zap className="h-3.5 w-3.5" />
                      DNS Configuration Helper
                      {dnsOpen ? (
                        <ChevronDown className="h-3.5 w-3.5 ml-auto" />
                      ) : (
                        <ChevronRight className="h-3.5 w-3.5 ml-auto" />
                      )}
                    </button>
                  </CollapsibleTrigger>
                  <AnimatePresence>
                    {dnsOpen && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.25 }}
                        className="overflow-hidden"
                      >
                        <div className="mt-3 space-y-2">
                          <p className="text-[11px] text-[#444444]">
                            Add the following DNS records to your domain registrar to configure your
                            custom domain:
                          </p>
                          {DNS_RECORDS.map((record) => (
                            <DnsRecordRow key={record.type + record.name} record={record} />
                          ))}
                          <div className="flex items-center gap-2 rounded-lg bg-[#00ff88]/5 border border-[#00ff88]/10 p-2.5">
                            <AlertTriangle className="h-3.5 w-3.5 text-[#00ff88] shrink-0" />
                            <p className="text-[11px] text-[#00ff88]/80">
                              DNS changes may take up to 48 hours to propagate globally.
                            </p>
                          </div>
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </Collapsible>
              </div>
            </GlassCard>

            {/* ── 5. Report Branding Section ───────────────────────────── */}
            <GlassCard className="p-6" delay={0.08}>
              <SectionHeader
                icon={<FileText className="h-4 w-4" />}
                title="Report Branding"
                description="Customize headers and footers for generated PDF reports"
              />
              <div className="space-y-5">
                <div className="space-y-2">
                  <Label className="text-[13px] font-medium text-[#444444] flex items-center gap-1.5">
                    <Type className="h-3 w-3" />
                    Report Header Text
                  </Label>
                  <Textarea
                    value={config.reportHeader}
                    onChange={(e) => update('reportHeader', e.target.value)}
                    className="bg-[#000000] border-white/[0.08] text-[#f0f0f0] placeholder:text-[#333333] min-h-[80px] resize-y"
                    placeholder="Confidential — Attack Surface Report"
                  />
                  <p className="text-[11px] text-[#333333]">
                    This text appears at the top of every generated PDF report
                  </p>
                </div>

                <div className="space-y-2">
                  <Label className="text-[13px] font-medium text-[#444444] flex items-center gap-1.5">
                    <Type className="h-3 w-3" />
                    Report Footer Text
                  </Label>
                  <Textarea
                    value={config.reportFooter}
                    onChange={(e) => update('reportFooter', e.target.value)}
                    className="bg-[#000000] border-white/[0.08] text-[#f0f0f0] placeholder:text-[#333333] min-h-[80px] resize-y"
                    placeholder="Generated by Acme Security ReconPro"
                  />
                </div>

                <Separator className="bg-white/[0.06]" />

                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2.5">
                      <ImageIcon className="h-4 w-4 text-[#444444]" />
                      <div>
                        <p className="text-[13px] font-medium text-[#f0f0f0]">
                          Include Company Logo
                        </p>
                        <p className="text-[11px] text-[#333333]">
                          Show the logo image in report headers
                        </p>
                      </div>
                    </div>
                    <Switch
                      checked
                      className="data-[state=checked]:bg-[#00ff88] data-[state=unchecked]:bg-[#21262d]"
                    />
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2.5">
                      <Eye className="h-4 w-4 text-[#444444]" />
                      <div>
                        <p className="text-[13px] font-medium text-[#f0f0f0]">
                          Hide &quot;Powered by ReconPro&quot;
                        </p>
                        <p className="text-[11px] text-[#333333]">
                          Remove ReconPro branding from reports and UI
                        </p>
                      </div>
                    </div>
                    <Switch
                      checked={config.hidePoweredBy}
                      onCheckedChange={(v) => update('hidePoweredBy', v)}
                      className="data-[state=checked]:bg-[#00ff88] data-[state=unchecked]:bg-[#21262d]"
                    />
                  </div>
                </div>
              </div>
            </GlassCard>

            {/* ── 6. Login Page Section ─────────────────────────────────── */}
            <GlassCard className="p-6" delay={0.10}>
              <SectionHeader
                icon={<LogIn className="h-4 w-4" />}
                title="Login Page"
                description="Customize the authentication page appearance"
              />
              <div className="space-y-5">
                <div className="space-y-2">
                  <Label className="text-[13px] font-medium text-[#444444]">
                    Custom Login Message
                  </Label>
                  <Textarea
                    value={config.loginPageMessage}
                    onChange={(e) => update('loginPageMessage', e.target.value)}
                    className="bg-[#000000] border-white/[0.08] text-[#f0f0f0] placeholder:text-[#333333] min-h-[80px] resize-y"
                    placeholder="Welcome to the Attack Surface Management Platform."
                  />
                </div>

                <div className="space-y-2">
                  <Label className="text-[13px] font-medium text-[#444444] flex items-center gap-1.5">
                    <ImageIcon className="h-3 w-3" />
                    Background Image URL
                  </Label>
                  <Input
                    value={config.faviconUrl}
                    onChange={(e) => update('faviconUrl', e.target.value)}
                    className="h-10 bg-[#000000] border-white/[0.08] text-[#f0f0f0] placeholder:text-[#333333]"
                    placeholder="https://yourcompany.com/login-bg.jpg"
                  />
                  <p className="text-[11px] text-[#333333]">
                    Optional — overrides the default dark background on the login page
                  </p>
                </div>

                <Separator className="bg-white/[0.06]" />

                <div className="space-y-2.5">
                  <Label className="text-[13px] font-medium text-[#444444] flex items-center gap-1.5">
                    <Layout className="h-3 w-3" />
                    Login Page Style
                  </Label>
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                    {/* Default */}
                    <LoginStyleCard
                      name="Default"
                      primaryColor={config.primaryColor}
                      selected={loginStyle === 'default'}
                      onClick={() => setLoginStyle('default')}
                    >
                      <div
                        className="w-full h-20 rounded-lg border border-white/[0.06] flex items-center justify-center relative overflow-hidden"
                        style={{ backgroundColor: config.accentColor || '#0a0d14' }}
                      >
                        <div className="absolute inset-0 bg-gradient-to-b from-transparent to-black/30" />
                        <div className="relative flex flex-col items-center gap-1.5 z-10">
                          <div
                            className="h-6 w-6 rounded-md text-[8px] font-bold flex items-center justify-center text-[#080a10]"
                            style={{ backgroundColor: config.primaryColor }}
                          >
                            {config.logoText || 'RP'}
                          </div>
                          <div className="w-16 h-1.5 rounded bg-white/10" />
                          <div className="w-12 h-1 rounded bg-white/10" />
                        </div>
                      </div>
                    </LoginStyleCard>

                    {/* Centered */}
                    <LoginStyleCard
                      name="Centered"
                      primaryColor={config.primaryColor}
                      selected={loginStyle === 'centered'}
                      onClick={() => setLoginStyle('centered')}
                    >
                      <div
                        className="w-full h-20 rounded-lg border border-white/[0.06] flex items-center justify-center"
                        style={{ backgroundColor: config.accentColor || '#0a0d14' }}
                      >
                        <div className="flex flex-col items-center gap-1.5">
                          <div className="rounded-lg border border-white/[0.08] bg-white/[0.03] p-2 flex flex-col items-center gap-1">
                            <div
                              className="h-5 w-5 rounded text-[7px] font-bold flex items-center justify-center text-[#080a10]"
                              style={{ backgroundColor: config.primaryColor }}
                            >
                              {config.logoText || 'RP'}
                            </div>
                            <div className="w-14 h-1.5 rounded bg-white/10" />
                            <div className="w-10 h-1 rounded bg-white/10" />
                          </div>
                        </div>
                      </div>
                    </LoginStyleCard>

                    {/* Split */}
                    <LoginStyleCard
                      name="Split"
                      primaryColor={config.primaryColor}
                      selected={loginStyle === 'split'}
                      onClick={() => setLoginStyle('split')}
                    >
                      <div
                        className="w-full h-20 rounded-lg border border-white/[0.06] flex overflow-hidden"
                        style={{ backgroundColor: config.accentColor || '#0a0d14' }}
                      >
                        <div
                          className="w-1/2 flex items-center justify-center"
                          style={{ backgroundColor: `${config.primaryColor}15` }}
                        >
                          <div
                            className="h-5 w-5 rounded text-[7px] font-bold flex items-center justify-center text-[#080a10]"
                            style={{ backgroundColor: config.primaryColor }}
                          >
                            {config.logoText || 'RP'}
                          </div>
                        </div>
                        <div className="w-1/2 flex items-center justify-center border-l border-white/[0.06]">
                          <div className="flex flex-col gap-1">
                            <div className="w-12 h-1.5 rounded bg-white/10" />
                            <div className="w-8 h-1 rounded bg-white/10" />
                          </div>
                        </div>
                      </div>
                    </LoginStyleCard>
                  </div>
                </div>
              </div>
            </GlassCard>

            {/* ── 7. Advanced Section ───────────────────────────────────── */}
            <GlassCard className="p-6" delay={0.12}>
              <Collapsible open={advancedOpen} onOpenChange={setAdvancedOpen}>
                <CollapsibleTrigger asChild>
                  <button className="flex items-center justify-between w-full cursor-pointer group">
                    <SectionHeader
                      icon={<Settings className="h-4 w-4" />}
                      title="Advanced Configuration"
                      description="Custom CSS, theme settings, import/export"
                    />
                    <motion.div
                      animate={{ rotate: advancedOpen ? 180 : 0 }}
                      transition={{ duration: 0.2 }}
                      className="ml-auto shrink-0 mt-1"
                    >
                      <ChevronDown className="h-4 w-4 text-[#444444] group-hover:text-[#f0f0f0] transition-colors" />
                    </motion.div>
                  </button>
                </CollapsibleTrigger>
                <AnimatePresence>
                  {advancedOpen && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3 }}
                      className="overflow-hidden"
                    >
                      <div className="mt-2 space-y-6">
                        {/* Custom CSS */}
                        <div className="space-y-2.5">
                          <Label className="text-[13px] font-medium text-[#444444] flex items-center gap-1.5">
                            <Code2 className="h-3 w-3" />
                            Custom CSS
                          </Label>
                          <div className="relative rounded-xl border border-white/[0.08] overflow-hidden">
                            <div className="flex items-center gap-2 px-3 py-1.5 bg-[#030407] border-b border-white/[0.06]">
                              <div className="flex gap-1.5">
                                <div className="h-2.5 w-2.5 rounded-full bg-[#ff8844]" />
                                <div className="h-2.5 w-2.5 rounded-full bg-[#ffaa00]" />
                                <div className="h-2.5 w-2.5 rounded-full bg-[#22c55e]" />
                              </div>
                              <span className="text-[10px] text-[#333333] font-mono ml-1">
                                custom-styles.css
                              </span>
                            </div>
                            <textarea
                              value={config.customCss}
                              onChange={(e) => update('customCss', e.target.value)}
                              className="w-full min-h-[160px] bg-[#030407] text-[#444444] font-mono text-xs p-4 resize-y focus:outline-none placeholder:text-[#30363d] leading-relaxed"
                              placeholder={`/* Custom CSS overrides */\n:root {\n  --brand-primary: ${config.primaryColor};\n}\n\n.sidebar-brand {\n  font-weight: 800;\n}`}
                            />
                          </div>
                          <p className="text-[11px] text-[#333333]">
                            CSS is injected into the application&apos;s head. Use sparingly.
                          </p>
                        </div>

                        <Separator className="bg-white/[0.06]" />

                        {/* Theme toggles */}
                        <div className="space-y-4">
                          <div className="flex items-center justify-between">
                            <div className="flex items-center gap-2.5">
                              <Moon className="h-4 w-4 text-[#444444]" />
                              <div>
                                <p className="text-[13px] font-medium text-[#f0f0f0]">
                                  Dark Mode
                                </p>
                                <p className="text-[11px] text-[#333333]">
                                  Enable dark interface by default
                                </p>
                              </div>
                            </div>
                            <Switch
                              checked={config.darkMode}
                              onCheckedChange={(v) => update('darkMode', v)}
                              className="data-[state=checked]:bg-[#00ff88] data-[state=unchecked]:bg-[#21262d]"
                            />
                          </div>

                          <div className="space-y-2.5">
                            <Label className="text-[13px] font-medium text-[#444444] flex items-center gap-1.5">
                              <Sun className="h-3 w-3" />
                              Default Theme
                            </Label>
                            <div className="flex items-center gap-2">
                              {(['dark', 'light', 'auto'] as const).map((t) => (
                                <motion.button
                                  key={t}
                                  whileHover={{ scale: 1.03 }}
                                  whileTap={{ scale: 0.97 }}
                                  onClick={() => update('theme', t)}
                                  className={`flex items-center gap-1.5 rounded-lg px-4 py-2 text-[13px] font-medium border transition-all cursor-pointer ${
                                    config.theme === t
                                      ? 'border-[#00ff88]/40 bg-[#00ff88]/10 text-[#00ff88]'
                                      : 'border-white/[0.06] bg-white/[0.02] text-[#444444] hover:text-[#f0f0f0] hover:border-white/[0.12]'
                                  }`}
                                >
                                  {t === 'dark' && <Moon className="h-3.5 w-3.5" />}
                                  {t === 'light' && <Sun className="h-3.5 w-3.5" />}
                                  {t === 'auto' && <Monitor className="h-3.5 w-3.5" />}
                                  {t.charAt(0).toUpperCase() + t.slice(1)}
                                </motion.button>
                              ))}
                            </div>
                          </div>
                        </div>

                        <Separator className="bg-white/[0.06]" />

                        {/* Import / Export */}
                        <div className="flex items-center gap-3">
                          <Button
                            variant="outline"
                            className="border-white/[0.08] text-[#444444] hover:text-[#f0f0f0] hover:bg-white/[0.04] gap-1.5"
                            onClick={handleExport}
                          >
                            <Download className="h-3.5 w-3.5" />
                            Export Configuration
                          </Button>
                          <Button
                            variant="outline"
                            className="border-white/[0.08] text-[#444444] hover:text-[#f0f0f0] hover:bg-white/[0.04] gap-1.5"
                            onClick={() => fileInputRef.current?.click()}
                          >
                            <Upload className="h-3.5 w-3.5" />
                            Import Configuration
                          </Button>
                          <input
                            ref={fileInputRef}
                            type="file"
                            accept=".json"
                            className="hidden"
                            onChange={handleImport}
                          />
                        </div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </Collapsible>
            </GlassCard>

            {/* ── 8. Status Bar ─────────────────────────────────────────── */}
            <GlassCard className="p-4" delay={0.14}>
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                <div className="flex items-center gap-4 flex-wrap">
                  <div className="flex items-center gap-2">
                    <Clock className="h-3.5 w-3.5 text-[#444444]" />
                    <span className="text-[12px] text-[#444444]">
                      Configuration last saved 2 hours ago
                    </span>
                  </div>
                  <Separator orientation="vertical" className="h-4 bg-white/[0.06] hidden sm:block" />
                  <div className="flex items-center gap-2">
                    <AlertTriangle className="h-3.5 w-3.5 text-yellow-400" />
                    <span className="text-[12px] text-[#444444]">
                      All changes require redeployment — estimated 5 minutes
                    </span>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <div className="flex items-center gap-1.5">
                    <div
                      className={`h-2 w-2 rounded-full animate-pulse ${
                        hasChanges ? 'bg-yellow-400' : 'bg-[#00ff88]'
                      }`}
                    />
                    <span
                      className={`text-[12px] font-medium ${
                        hasChanges ? 'text-yellow-400' : 'text-[#00ff88]'
                      }`}
                    >
                      {hasChanges ? 'Unsaved Changes' : 'Deployment Active'}
                    </span>
                  </div>
                </div>
              </div>
            </GlassCard>
          </motion.div>

          {/* ── Right Sidebar: Live Preview (XL screens) ──────────────── */}
          <div className="hidden xl:block">
            <div className="sticky top-8 space-y-4">
              <GlassCard className="p-5" delay={0.05}>
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-2">
                    <Monitor className="h-4 w-4 text-[#00ff88]" />
                    <h3 className="text-sm font-semibold text-[#f0f0f0]">Live Preview</h3>
                    <Badge className="bg-[#00ff88]/10 text-[#00ff88] border-[#00ff88]/20 text-[10px] px-1.5 py-0">
                      REAL-TIME
                    </Badge>
                  </div>
                </div>
                <LivePreview config={config} />

                <Separator className="bg-white/[0.06] my-4" />

                {/* Color summary */}
                <div className="space-y-2.5">
                  <p className="text-[11px] font-medium text-[#444444] uppercase tracking-wider">
                    Active Colors
                  </p>
                  <div className="grid grid-cols-2 gap-2">
                    <div className="flex items-center gap-2 rounded-lg bg-white/[0.02] border border-white/[0.04] p-2">
                      <div
                        className="h-6 w-6 rounded-md border border-white/10"
                        style={{ backgroundColor: config.primaryColor }}
                      />
                      <div>
                        <p className="text-[10px] text-[#333333]">Primary</p>
                        <p className="text-[11px] font-mono text-[#f0f0f0]">
                          {config.primaryColor}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center gap-2 rounded-lg bg-white/[0.02] border border-white/[0.04] p-2">
                      <div
                        className="h-6 w-6 rounded-md border border-white/10"
                        style={{ backgroundColor: config.accentColor }}
                      />
                      <div>
                        <p className="text-[10px] text-[#333333]">Accent</p>
                        <p className="text-[11px] font-mono text-[#f0f0f0]">
                          {config.accentColor}
                        </p>
                      </div>
                    </div>
                  </div>
                </div>

                <Separator className="bg-white/[0.06] my-4" />

                <Dialog open={previewOpen} onOpenChange={setPreviewOpen}>
                  <DialogTrigger asChild>
                    <Button
                      className="w-full bg-[#00ff88] text-[#080a10] hover:bg-[#00ff88]/90 font-semibold gap-1.5"
                    >
                      <ExternalLink className="h-3.5 w-3.5" />
                      Full Preview
                    </Button>
                  </DialogTrigger>
                  <DialogContent className="bg-[#080b14] border-white/[0.08] text-[#f0f0f0] sm:max-w-4xl max-h-[85vh] overflow-y-auto">
                    <DialogHeader>
                      <DialogTitle className="text-[#f0f0f0] flex items-center gap-2">
                        <Monitor className="h-4 w-4 text-[#00ff88]" />
                        Full Preview
                      </DialogTitle>
                    </DialogHeader>
                    <FullPreviewModal config={config} />
                  </DialogContent>
                </Dialog>
              </GlassCard>

              {/* Quick Stats */}
              <GlassCard className="p-4" delay={0.07}>
                <p className="text-[11px] font-medium text-[#444444] uppercase tracking-wider mb-3">
                  Brand Summary
                </p>
                <div className="space-y-2">
                  {[
                    { label: 'Product', value: config.productName },
                    { label: 'Company', value: config.companyName },
                    { label: 'Theme', value: config.theme },
                    { label: 'Custom Domain', value: config.customDomain || 'Not set' },
                    { label: 'White-Label', value: config.hidePoweredBy ? 'Active' : 'Partial' },
                  ].map((item) => (
                    <div
                      key={item.label}
                      className="flex items-center justify-between text-[12px]"
                    >
                      <span className="text-[#333333]">{item.label}</span>
                      <span
                        className={`font-medium ${
                          item.label === 'White-Label' && config.hidePoweredBy
                            ? 'text-[#00ff88]'
                            : 'text-[#f0f0f0]'
                        }`}
                      >
                        {item.value}
                      </span>
                    </div>
                  ))}
                </div>
              </GlassCard>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
