trigger:
  - main
variables:
  imageName: 'reconpro'
  imageTag: '11.0.0'
stages:
- stage: Build
  jobs:
  - job: Build
    pool: { vmImage: 'ubuntu-latest' }
    steps:
    - script: npm ci && npm run build
- stage: Deploy
  dependsOn: Build
  jobs:
  - job: Deploy
    pool: { vmImage: 'ubuntu-latest' }
    steps:
    - script: echo 'Deploy step'
